apiVersion: automationbroker.io/v1alpha1
kind: AutomationBroker
metadata:
  name: ansible-service-broker
  namespace: openshift-ansible-service-broker
spec:
  createBrokerNamespace: 'false'
  brokerConfig:
    registry:
      - type: dockerhub
        name: docker
        url: https://registry.hub.docker.com
        org: ansibleplaybookbundle
        fail_on_error: false
        white_list:
          - ".*-apb$"
      - type: local_openshift
        name: lo
        namespaces:
          - openshift
        white_list:
          - ".*-apb$"
    dao:
      type: crd
    log:
      logfile: /var/log/ansible-service-broker/asb.log
      stdout: true
      level: debug
      color: true
    openshift:
      host: ""
      ca_file: ""
      bearer_token_file: ""
      image_pull_policy: IfNotPresent
      sandbox_role: "edit"
      namespace: openshift-ansible-service-broker
      keep_namespace: false
      keep_namespace_on_error: true
    broker:
      bootstrap_on_startup: true
      dev_broker: true
      launch_apb_on_bind: false
      recovery: true
      output_request: true
      ssl_cert_key: /etc/tls/private/tls.key
      ssl_cert: /etc/tls/private/tls.crt
      refresh_interval: "600s"
      auth:
        - type: basic
          enabled: false
